acl my_allowed_ip src 213.137.244.9
acl localhost src 127.0.0.1/32 ::1
acl localnet src 192.168.0.0/16 172.16.0.0/12 10.0.0.0/8
http_access allow my_allowed_ip
http_access allow localhost
http_access allow localnet
http_access deny all

http_port 3128
# https_port 3129 cert=/etc/squid/ssl_cert.crt key=/etc/squid/ssl_cert.key generate-host-certificates=on

# ACLs для подключения через HTTPS
acl SSL_ports port 443
acl CONNECT method CONNECT

# Разрешить подключения по протоколу CONNECT к SSL портам
http_access allow CONNECT SSL_ports

# Определяем безопасные порты
acl Safe_ports port 3128
acl Safe_ports port 3129
acl Safe_ports port 80
acl Safe_ports port 443

# Разрешаем доступ к безопасным портам
http_access allow Safe_ports

# Логирование доступа
access_log /var/log/squid/access.log

# squid -k parse
# apt update && apt-get install squid-openssl
# systemctl status squid
# service squid stop
# service squid restart
# scp squid.conf root@46.8.29.47:/etc/squid/squid.conf

# chmod 400 /etc/squid/ssl_cert.key
# chmod 444 /etc/squid/ssl_cert.crt
# openssl s_client -connect 185.221.213.169:3129 -showcerts
# curl -x http://185.221.213.169:3128 http://example.com
# curl -x https://185.221.213.169:3129 --cacert /etc/squid/ssl_cert.crt -I https://api.github.com/organizations
