# /etc/postgresql/pg_hba.conf
# repl
hostnossl    replication    all    213.137.244.0/32    md5
hostnossl    all            all    213.137.244.0/32    md5

# local: socket only (no password)
local   all        all                    peer

# localhost IPv4 only (no password)
host    all        all        127.0.0.1/32    trust
host    all         all     127.0.0.1/32    scram-sha-256

# localhost IPv6 only (no password)
host    all        all        ::1/128         trust
host    all         all    ::1/128         scram-sha-256

# Docker
host    all    all    172.16.0.0/12    md5
host    all    all    192.168.0.0/16   md5

# MY SERVERs
host    all    all    185.221.213.245/32    md5
host    all    all    185.221.213.245/32    scram-sha-256


# MY IPs
host    all        all        213.137.244.0/24 md5

# everything else rejected
host    all        all        0.0.0.0/0           reject
