# /etc/postgresql/postgresql.base.conf

hba_file = '/etc/postgresql/pg_hba.conf'
# ident_file = '/var/lib/postgresql/18/CLUSTER/pg_ident.conf'
# find /var/lib/postgresql/18/CLUSTER/pg_log -type f -exec cat {} +

listen_addresses = '*'

max_connections = 100

work_mem = 16MB
wal_buffers = -1
shared_buffers = 16MB
synchronous_commit = off

# timezone = 'Europe/Moscow'

# WAL
wal_level = 'logical'
max_wal_size = 1GB
min_wal_size = 80MB

ssl = on
ssl_cert_file = 'server.crt'
ssl_key_file = 'server.key'

# logs
logging_collector = on
# logging_collector = on
log_directory = 'pg_log'
log_filename = 'postgresql-%Y-%m-%d_%H%M%S.log'
# log_statement = 'all'
log_connections = off
log_rotation_age = 1d
log_rotation_size = 100MB
log_truncate_on_rotation = on
log_min_messages = warning
