on:
  push:
    branches: [ main ]
    paths:
      - 'postgres/**'
      - '.github/workflows/*-github-runner.yaml'
  workflow_dispatch:

jobs:
  docker_build:
    uses: petrochenkov-ak-lab/.github/.github/workflows/base-docker-image.yaml@main
    with:
      image_name: 'github-runner'
      image_tag: 'latest'
      dockerfile: './github-runner/Dockerfile'
