on:
  push:
    branches: [ main ]
    paths:
      - 'postgres/**'
      - '.github/workflows/*-postgres.yaml'
  workflow_dispatch:

jobs:
  docker_build:
    uses: petrochenkov-ak-lab/.github/.github/workflows/base/docker/build/image.yml@main
    with:
      image_name: 'postgres'
      image_tag: '18'
      dockerfile: './postgres/Dockerfile'

