name: Deploy Postgres

on:
  push:
    branches: [ main ]
    paths:
      - 'postgres/**'
      - '.github/workflows/docker-postgres.yaml'
  workflow_dispatch:

jobs:
  docker_build:
    uses: ./.github/workflows/docker-build.yml@main
    with:
      image_name: 'postgres'
      image_tag: '18'
      dockerfile: './postgres/Dockerfile'

