on:
  push:
    branches: [ main ]
    paths:
      - .github/workflows/docker-github-runner-build.yaml
      - 'github-runner/**'
  workflow_dispatch:

jobs:
  docker_build:
    permissions:
      contents: read
      packages: write
    uses: petrochenkov-ak-lab/.github/.github/workflows/base-docker-build.yaml@main
    with:
      image_name: 'github-runner'
      image_tag: 'latest'
      dockerfile: './github-runner/Dockerfile'
