name: docker-github-runner.yaml

on:
  push:
    branches: [ main ]
    paths:
      - 'postgres/**'
      - '.github/workflows/docker-github-runner.yaml'
  workflow_dispatch:

jobs:
  docker_build:
    uses: ./.github/workflows/docker-build.yml
    with:
      image_name: 'github-runner'
      image_tag: 'latest'
      dockerfile: './github-runner/Dockerfile'
